title: buildlog
email: your-email@example.com
description: >-
  사소한 기록을 차곡차곡 쌓아, 나만의 이야기를 만들어갑니다.
  Quietly stacking little notes — shaping them into my own story.
  小さな記録を積み重ねて、私だけの物語にしていく。
baseurl: "/buildlog"
url: "https://yejin-space.github.io"
twitter_username: yejinspace
github_username: yejin-space
remote_theme: minimal-mistakes-jekyll

plugins:
  - jekyll-feed
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
